### ISSUE TITLE
Hi，看到您的WWDC15的project

### ISSUE THREAD

**Issue by lvlingsheng** [Schemetrical/WWDC15#1]
感觉您做的非常好，为啥最后被拒了？是因为不能用Cocoapods么？有这样的规定么？

**Comment by Schemetrical** [comment]
没有这样的规定，不知道为什么被拒绝了。我认为关于编程的内容太少了。

**Comment by lvlingsheng** [comment]
你前年是不是也投过？前年有用cocoapod这类的么？今年你还投么？

**Comment by Schemetrical** [comment]
前年投过，进了。前年没用cocoapod，但上年有些用cocoapods的人也进了。今年还投的。

**Comment by lvlingsheng** [comment]
好，希望能在SF见，哈哈，这也是我最后一次机会了。感觉用Cocoapods有点冒险，虽然没说，但是我统计了一下去年的这个页面：https://github.com/wwdc/2015，基本挂的全都是用了cocoapods的，过的都是没用的。

**Comment by Schemetrical** [comment]
：）
有点尴尬的是创建网站的人都被拒绝了😄

**Comment by lvlingsheng** [comment]
哈哈，加油，你是还在上高中么？

**Comment by Schemetrical** [comment]
高二，还有今年和明年可以申请。

**Comment by lvlingsheng** [comment]
好嘞，以后多交流

**Comment by Schemetrical** [comment]
一定！
